### ISSUE TITLE
Different extract directory

### ISSUE THREAD

**Issue by pratikdhaboo** [SidKumarSingh/CodeIgniter-Bundle-for-Aptana#1]
I was not able to locate <AptanaDirectory>/configuration/org.eclipse.osgi/bundles/75/1/.cp/bundles
I did a directory search which revealed <AptanaDirectory>/configuration/org.eclipse.osgi/bundles/502/1/.cp/bundles as the deepest "bundles" path.

Extracting to this folder and restarting Aptana 3 served the purpose.

**Comment by SidKumarSingh** [comment]
Thanks Pratik. The thing is 502 may be specific for you because mine turned up in 348. I'm going to figure out how the bundle can be installed seamlessly by everyone irrespective of the evidently varying directory setup. Please bear with me till then.

**Comment by SidKumarSingh** [comment]
There was a slight change in how rubles are handled in Aptana Studio 3. Please follow the following instructions for installing the ruble. Will update the readme accordingly.
- Mac/Linux: $home/Documents/Aptana 
- Everywhere else: ${user.home}/Aptana Rubles. On Windows, that would translate to somewhere like c:\Users\Username\Aptana Rubles
- If you still can't find the location, look for your user.home java property. Open up the "About Studio" menu, then Installation Details > Configuration and search for the user.home property.

Issue closed.
